### PR TITLE
#1299 Message signing fixes

### LINKED ISSUE #1299: Better design for message signing
image
image

Do we have designs for this view?
@SergejSoft @falinebambi

### PR DESCRIPTION
**Pull request by lizonp**
#1299

### CODE REVIEW

File: app/components/dashboard/eto-list/EtoList.tsx [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { FormattedMessage } from "react-intl-phraseapp";
 import { Col } from "reactstrap";
 import { compose } from "redux";
 
+import { setDisplayName } from "recompose";
```
Comment (desfero) [inline app/components/dashboard/eto-list/EtoList.tsx]: please move `recompose` to the line 6 and add empty line between third-party imports and local one

File: app/components/modals/txSender/shared/ErrorMessage.tsx [hunk 2]
```diff
@@ -0,0 +1,18 @@
+import * as React from 'react';
+import { FormattedMessage } from 'react-intl';
```
Comment (desfero) [inline app/components/modals/txSender/shared/ErrorMessage.tsx]: Use r`eact-intl-phraseapp` please

File: app/components/modals/txSender/shared/ErrorMessage.tsx [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+  return (
+    <div data-test-id="modals.shared.signing-message.modal">
+    <img src={failedImg} className={styles.eth} />;
+    <h3 className={styles.title}><FormattedMessage id="modal.shared.signing-message.modal.transaction-error.title"/></h3>
+    <p className={styles.hint}><FormattedMessage id="modal.shared.signing-message.modal.transaction-error.hint"/></p>
+  </div>
+  )
+}
+
+export { ErrorMessage }
```
Comment (desfero) [inline app/components/modals/txSender/shared/ErrorMessage.tsx]: 👍

File: app/components/modals/txSender/shared/ErrorMessage.tsx [hunk 4]
```diff
@@ -0,0 +1,18 @@
+import * as React from 'react';
+import { FormattedMessage } from 'react-intl';
+
+import * as styles from "./ErrorMessage.module.scss";
+
+import * as failedImg from "../../../../assets/img/ether_fail.svg";
+
+const ErrorMessage: React.SFC = () => {
+  return (
+    <div data-test-id="modals.shared.signing-message.modal">
```
Comment (desfero) [inline app/components/modals/txSender/shared/ErrorMessage.tsx]: some problems with formatting here, as `div` on line 14 is not aligned with the one on line 10

File: app/config/.env.example [hunk 5]
```diff
@@ -16,7 +16,6 @@ NF_ISSUERS_ENABLED=1
 NF_EQUITY_TOKEN_OFFERINGS_VISIBLE=1
 NF_ETO_LOAD_REAL_DATA=0
 NF_FOUNDERS_BANK_VISIBLE=1
-NF_PORTFOLIO_PAGE_VISIBLE=0
```
Comment (desfero) [inline app/config/.env.example]: @Moejoe90 do we want to remove NF_PORFTOLIO_PAGE_VISIBLE flag?

File: app/modules/public-etos/types.ts [hunk 6]
```diff
@@ -0,0 +1,41 @@
+import BigNumber from "bignumber.js";
```
Comment (desfero) [inline app/modules/public-etos/types.ts]: That file should not be a part of the pull request.

File: intl/locales/en-en.json [hunk 7]
```diff
@@ -444,6 +444,10 @@
   "modal.sent-eth.gas-price": "Gas price",
   "modal.sent-eth.title": "Withdraw ether",
   "modal.sent-eth.to-address": "To address",
+  "modal.shared.signing-message.modal.hint": "Please accept message on your signer to proceed with the transcation.",
+  "modal.shared.signing-message.modal.title": "Signing Transaction",
+  "modal.shared.signing-message.modal.transaction-error.hint": "Sorry an error has occured with your transaction. Please close this module and try again.",
+  "modal.shared.signing-message.modal.transaction-error.title": "transaction error",
```
Comment (desfero) [inline intl/locales/en-en.json]: Maybe `Transaction error` (capitalize)?

File: app/components/modals/txSender/shared/SigningMessage.module.scss [hunk 8]
```diff
@@ -0,0 +1,14 @@
+.hint,
```
Comment (desfero) [inline app/components/modals/txSender/shared/SigningMessage.module.scss]: `SigningMessage` and `ErrorMessage` are almost identical so need to extract what is the same to separate component.

```
import * as React from 'react';
import { FormattedMessage } from 'react-intl-phraseapp';

 import * as styles from "./Message.module.scss";
 import * as failedImg from "../../../../assets/img/ether_fail.svg";

type TProps = {
   "data-test-id": string;
   title: React.Element;
   hind: React.element;
   image?: React.Element.
}

 const Message: React.SFC<TProps> = (props) => {
  return (
    <div data-test-id="props["data-test-id"]">
    {props.image}
    <h3 className={styles.title}>{props.title}</h3>
    <p className={styles.hint}>{props.hint}</p>
  </div>
  )
}
 export { ErrorMessage }

File: app/components/modals/txSender/shared/ErrorMessage.tsx [hunk 9]
```diff
@@ -0,0 +1,21 @@
+import * as React from "react";
+import { FormattedMessage } from "react-intl-phraseapp";
+
+import * as styles from "./ErrorMessage.module.scss";
+
+import * as failedImg from "../../../../assets/img/ether_fail.svg";
+import { Message } from "./Message";
```
Comment (desfero) [inline app/components/modals/txSender/shared/ErrorMessage.tsx]: Import should be one line below `react-intl-phraseapp`

File: app/components/modals/txSender/shared/ErrorMessage.tsx [hunk 10]
```diff
@@ -0,0 +1,21 @@
...
+
+const ErrorMessage: React.SFC = () => {
+  return (
+    <div data-test-id="modals.shared.signing-message.modal">
```
Comment (desfero) [inline app/components/modals/txSender/shared/ErrorMessage.tsx]: `div` can be removed here as it's possible to pass `date-test-id` as a prop to `Message`. Same with `SigningMessage`

File: intl/locales/en-en.json [hunk 11]
```diff
@@ -489,6 +489,10 @@
   "modal.sent-eth.gas-price": "Gas price",
   "modal.sent-eth.title": "Withdraw ether",
   "modal.sent-eth.to-address": "To address",
+  "modal.shared.signing-message.modal.hint": "Please accept message on your signer to proceed with the transcation.",
+  "modal.shared.signing-message.modal.title": "Signing Transaction",
+  "modal.shared.signing-message.modal.transaction-error.hint": "Sorry an error has occured with your transaction. Please close this module and try again.",
```
Comment (desfero) [inline intl/locales/en-en.json]: `Please close this **modal**...`?
