### PR TITLE
Removes seed validation/ Fixes paths

### LINKED ISSUE #168: There should be no recover phrase view after registration

### LINKED ISSUE #169: Current routes should be /register not /login

### PR DESCRIPTION
**Pull request by Moejoe90**
Fixes #168  Removes Seed Validation
Fixes #169 Changes Paths

### CODE REVIEW

File: app/components/walletSelector/walletLight/WalletLightRoutes.tsx [hunk 1]
```diff
@@ -5,5 +5,4 @@ const parentRoutePath = walletRoutes.light;
 export const walletLightRoutes = {
```
Comment (krzkaczor) [inline app/components/walletSelector/walletLight/WalletLightRoutes.tsx]: why did you change capitalisation of this file? We uppercase only files exporting classes.

Comment (Moejoe90) [reply app/components/walletSelector/walletLight/WalletLightRoutes.tsx]: Ah i assumed this file was forgotten will change back now
