### PR TITLE
Fix wallet calcs

### LINKED ISSUE #442: incorrect wallet balances, ETH/EUR ICBM probably mixed up
I have 1000 EURT and 10 ETH in LockedAccount.
I also have 136 ETH in simple accounts

It seems you add EURT to ETH, see above

### PR DESCRIPTION
**Pull request by krzkaczor**
closes #442

### CODE REVIEW

File: app/modules/wallet/selectors.ts [hunk 1]
```diff
@@ -29,13 +29,16 @@ export const selectLockedWalletHasFunds = (state: IWalletStateData): boolean =>
  * ICBM Wallet Assets
  */
 export const selectICBMLockedEtherBalance = (state: IWalletStateData) =>
-  state.euroTokenICBMLockedBalance;
+  state.etherTokenICBMLockedBalance;
```
Comment (Moejoe90) [inline app/modules/wallet/selectors.ts]: :(

**Comment by krzkaczor** [comment]
@Moejoe90 it uses WEIs in calculations. Data is kept as strings in WEI (no precision lost)  and it's converted to bignumbers when modified and back to strings.
