### PR TITLE
fixes backCodeVerified when wallet is not neuWallet

### LINKED ISSUE #412: Remove notification when logged in with MetaMask

### PR DESCRIPTION
**Pull request by Moejoe90**
fixes #412

### CODE REVIEW

File: app/modules/notifications/reducer.ts [hunk 1]
```diff
@@ -68,3 +69,6 @@ export const seedNotBackedUpNotification = () => ({
   actionLinkText: "Go to settings",
   onClickAction: routingActions.goToSettings(),
 });
+
+export const selectseedNotBackedUpNotification = (state: IAuthState) =>
```
Comment (krzkaczor) [inline app/modules/notifications/reducer.ts]: `Seed` instead of `seed`
